### ISSUE TITLE
Add Submariner.app to homebrew-cask

### ISSUE THREAD

**Issue by cmarhoover** [NattyNarwhal/Submariner#127]
I attempted to add the latest version of Submariner to the homebrew-cask repo, but the commit was rejected because active development on Submariner is occurring on this fork without pushing changes upstream. 

Closed pull request here: https://github.com/Homebrew/homebrew-cask/pull/146138#issuecomment-1528443121

Relevant discussion on creating casks from forks here: https://github.com/Homebrew/homebrew-cask/issues/142510

**Comment by NattyNarwhal** [comment]
There was what I read as [implicit approval in upstream](https://github.com/Read-Write/Submariner/issues/3), but I don't know if that helps you.

**Comment by cmarhoover** [comment]
Thanks! That thread was sufficient, and my pull request was merged here:  https://github.com/Homebrew/homebrew-cask/pull/146454. Submariner.app v2.2 is now installable through homebrew!
