### ISSUE TITLE
Miniumum requirements (unable to run on Catalina 10.15)

### ISSUE THREAD

**Issue by dmaltsiniotis** [NattyNarwhal/Submariner#131]
Is there any chance to support older versions of macOS? I get this when attempting the run the newest 2.2 version:

![image](https://user-images.githubusercontent.com/106233/236538265-842bec50-8961-4e19-ae08-441bd07f1a5c.png)

If it's not possible to support 10.15 (Catalina), we should probably add a minimum specs section to the README.

Thank you!

-DM

**Comment by NattyNarwhal** [comment]
It does require 11. I'll make a note of this.
