### ISSUE TITLE
Get a new Big Sur style icon

### ISSUE THREAD

**Issue by NattyNarwhal** [NattyNarwhal/Submariner#52]
I actually like the spirit of the current one (look like the hatch of an old submarine, 1000 leagues under the sea kinda vibes), though there are some issues like the actual musical note icon and the inner part inside of the hatch looking a bit weird. It'd be nice to make it a RoundRect too.

Notes from a friend:

> uhhh, the usual suspects to go to would be places like theiconfactory or louie mantia
> but also look at the artists who do the apollo ultra icons on /r/ApolloApp
> Christian is probably a good person to ask for this sort of thing

**Comment by NattyNarwhal** [comment]
This is sometihng I want to do, but I don't want it to block a 2.0.

**Comment by NattyNarwhal** [comment]
MAS wants a 512px@2X icon, so publishing to MAS blocks on this.

**Comment by Porco-Rosso** [comment]
I've been using this icon. Would be nice to have something along these lines with a hatch in the place of the tape spool.
https://macosicons.com/#/Magnetola
<img width="101" alt="image" src="https://user-images.githubusercontent.com/7024527/217752426-76afa1fd-b99a-40fe-855d-d54c9c58a443.png">

**Comment by NattyNarwhal** [comment]
I'm in contact with a designer about this; his schedule is free in March, so we'll see movement on it then.
