### ISSUE TITLE
audio/x-flac format files cannot be played

### ISSUE THREAD

**Issue by BigNerdCoding** [NattyNarwhal/Submariner#89]
If the SBTrack file format is audio/x-flac, we cannot successfully play the music through the stream interface in SBPlayer

**Comment by NattyNarwhal** [comment]
Huh, what causes a file to get considered as x-flac instead of flac? I haven't seen this before with mine, but I wouldn't doubt the system UTI guessing code to be wrong.

**Comment by NattyNarwhal** [comment]
Unsure still, but I merged #90 if it helps. I think that should solve it, but let me know if there's more to this/reopen it.

**Comment by BigNerdCoding** [comment]
> Unsure still, but I merged #90 if it helps. I think that should solve it, but let me know if there's more to this/reopen it.

Thanks
