### ISSUE TITLE
Authentication Method

### ISSUE THREAD

**Issue by lorenzgillner** [NattyNarwhal/Submariner#92]
I'm trying to connect to a subsonic server that uses password authentication. Since I can't change the server config to use token authentication, I can't use the application at all. I would like to request the option of choosing between authentication methods when adding a new server.

**Comment by NattyNarwhal** [comment]
https://github.com/NattyNarwhal/Submariner/blob/master/Submariner/SBServer.m#L349-L363

I should un-hardcode this :sweat_smile:

**Comment by NattyNarwhal** [comment]
I've added this for the next version. You can try compiling it yourself (should be a normal Xcode project), or using the output from [CI](https://github.com/NattyNarwhal/Submariner/actions) (be warned that those builds aren't signed). Note that this fix does involve a schema upgrade, so it'll be incompatible with 2.0.
