### ISSUE TITLE
Playlists are in Random order

### ISSUE THREAD

**Issue by Porco-Rosso** [NattyNarwhal/Submariner#97]
Thanks for the great software, works and looks great with my Navidrome server! 

Unfortunately I find that the playlists loaded are displayed in a random (or seemingly random?) order in the sidebar. 
Would it be possible to sort these alphabetically or by recency? Not sure I've seen the latter implemented anywhere, but might be possible.

**Comment by NattyNarwhal** [comment]
Are you talking about the local playlists, or playlists on the server? The former seems to be order of creation AFAIK, but the latter seems kinda random.

**Comment by Porco-Rosso** [comment]
I'm talking about playlists on the server. I haven't tried local playlists. 
I guess an option to sort them in the menubar or preferences would be sufficient.
